### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by z-jiaming** [Tsingularity/dift#21]
Thanks for your great work!
I try the eval_davis.py with adm model after create with `conda env create -f environment.yml`.
<img width="667" alt="Snipaste_2024-01-15_20-29-02" src="https://github.com/Tsingularity/dift/assets/42411674/7b4b78a2-fd49-4a0b-be4e-e64e2b889964">

But it raise a cuda error:
<img width="1109" alt="Snipaste_2024-01-15_20-21-50" src="https://github.com/Tsingularity/dift/assets/42411674/d1db02a8-6dad-4f5f-b5c2-eb977d041498">

I passed CUDA_LAUNCH_BLOCKING=1, then:
<img width="1178" alt="Snipaste_2024-01-15_20-16-12" src="https://github.com/Tsingularity/dift/assets/42411674/f24a75d7-d3ea-4b2b-87de-1e4906ee5e07">

I try to delete codes which may have an effect, including `gc.collect()` and 'torch.cuda.empty_cache()',. but it doesn't work.

Would you mind help me to slove this?
Thanks a lot!

**Comment by Tsingularity** [comment]
This seems to imply GPU is out of memory. Could you try decrease the `n_last_frames` argument? This would lead to very marginal performance drop though.

**Comment by z-jiaming** [comment]
Thanks for your reply!
I decrease the `n_last_frames `argument and it works.
Could you please tell me the GPU memory requires in your standard setup?

**Comment by Tsingularity** [comment]
The video experiments are done on A100.

**Comment by z-jiaming** [comment]
Is it the 80G version?

**Comment by Tsingularity** [comment]
yes
